### ISSUE TITLE
Genshi doesn't support Python 3.8

### ISSUE THREAD

**Issue by hodgestar** [edgewall/genshi#14]
It's the usual AST changes that break Genshi on every Python release.

From the original Genshi tracker bug report https://genshi.edgewall.org/ticket/612:

> Python 3.8 now uses ast.Constant type and remove types like _ast.Str: ast.Str is a backward compatibility class.
>
> I had to disable Genshi benchmark in the performance project: ​https://github.com/python/performance/issues/46
>
> Example of issue: "strarg = _new(_ast.Str, node.id)" at genshi/template/eval.py:616: the code should use ast.Str, not _ast.Str.

See also https://bugs.python.org/issue32892.

Update: And the Python 3.8 release schedule -- https://www.python.org/dev/peps/pep-0569/ (release currently scheduled for 20 October 2019).

**Comment by FelixSchwarz** [comment]
I assume nobody came up with a patch so far? (Fedora is preparing a Python 3.8 upgrade and unsurprisingly Genshi fails to build.)

downstream issue is [Fedora bug 1693485: "python-genshi FTBFS with Python3.8"](https://bugzilla.redhat.com/show_bug.cgi?id=1693485)

**Comment by hroncok** [comment]
I have a fix ready. Running tox to see if I broke something. I'm afraid I no longer have Python 2.5 around.

**Comment by hroncok** [comment]
https://github.com/edgewall/genshi/pull/16
