### ISSUE TITLE
Provide a py2 manylinux1 wheel

### ISSUE THREAD

**Issue by thmo** [edgewall/genshi#20]
Would it be possible (e.g. using Travis and the pypa Images) to build and provide more wheels, especially a py2 wheel with speedups, in the manylinux1 variant?

**Comment by hodgestar** [comment]
I'm not personally planning to add support for building wheels with the speed up for releases, but any contributions to the release GitHub action to do so would not be unwelcome.

**Comment by hodgestar** [comment]
Closing this but contributions of GitHub actions or other solutions for providing pre-build wheels with the speedups module precompiled are still welcome.
