### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by kreyoo** [edgewall/genshi#60]
Is it possible to create a new Release?

The fix in PR #57 is the only thing that keeps me from upgrading my project to Python 3.9 and up
and I dislike fetching dependencies from git.

Would be great if it's possible 👍🏻

**Comment by FelixSchwarz** [comment]
Would be nice for Fedora as well. We just added the Python 3.11 patch for Fedora's RPM but of course it would be nicer to just use a release tarball.

**Comment by hodgestar** [comment]
I've finally found some time to rewrite the old Travis deployment using GitHub Actions. The PR for it is https://github.com/edgewall/genshi/pull/61. Once that is working we can do a new release.

**Comment by FelixSchwarz** [comment]
Release has been published - thank you, Simon :-)

**Comment by brandtbucher** [comment]
Thanks a ton for putting this out!

**Comment by hodgestar** [comment]
Pleasure!
