### ISSUE TITLE
Error "Flags not at the start of the expression" in recent Python 3.11

### ISSUE THREAD

**Issue by gvanrossum** [edgewall/genshi#66]
It seems a deprecated `re` feature was recently removed, and Genshi as a result fails under 3.11 built from the latest source (as of March 22 at least).

More color here: https://github.com/faster-cpython/ideas/issues/333#issuecomment-1076479303

**Comment by gvanrossum** [comment]
Apparently this is fixed in https://github.com/edgewall/genshi/commit/605de3bfdda3ae80dc2aa1676901dae37c6eb031 -- can anyone confirm? And then do a release, pretty please?

**Comment by hodgestar** [comment]
Genshi 0.7.7 released with the regex fixes included.

**Comment by gvanrossum** [comment]
Thanks!
