### ISSUE TITLE
Add support for Python 3.12 and 3.13.

### ISSUE THREAD

**Issue by hodgestar** [edgewall/genshi#80]
Currently tests with Python 3.12 fail because of the usual Python AST changes.

**Comment by FelixSchwarz** [comment]
Interestingly the test suite for Genshi 0.7.7 works in Fedore for 3.12 and 3.13 so it has to be one of the recent changes for 0.7.8 which triggers the test failure. Maybe it was broken already in 3.12 and nobody noticed but for the record, this is the only patch Fedora ships for Genshi: https://src.fedoraproject.org/rpms/python-genshi/blob/rawhide/f/python-genshi-use-default-test-loader.patch

**Comment by hodgestar** [comment]
The master branch now supports Python 3.12.

@FelixSchwarz I also applied the Fedora patch.

**Comment by hodgestar** [comment]
Support for Python 3.13 added in #81.

**Comment by mgorny** [comment]
Thanks a lot!
